### ISSUE TITLE
/feature looks crappy compared to /features

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/chromium-dashboard#406]
### `/feature`

![image](https://cloud.githubusercontent.com/assets/39191/18185402/592f103a-7052-11e6-887a-e121eb27856c.png)
### `/features`

![image](https://cloud.githubusercontent.com/assets/39191/18185406/5c4fdc90-7052-11e6-816a-2164d411f513.png)

I was real confused because I clicked over to `/feature` from mozilla's platform status tracker, and I was like..

![](https://media.giphy.com/media/D85DeTnI64xLq/giphy.gif)

**Comment by ebidel** [comment]
Total 💩 . It might be nice to explore just using `<chromedash-feature>` directly on this page. IT would have all the same styling and the google bot runs JS. Would be good to verify SEO stays intake after that move.

**Comment by ebidel** [comment]
Now that we have the embed mode (https://www.chromestatus.com/feature/6691520493125632?embed), we should consider making these pages nicer. It'll look great in our docs.

cc @PaulKinlan

**Comment by caitp** [comment]
I've just filed an issue on behalf of @littledan and @thejoshwolfe, and the /feature/ view looks even worse than the example provided above (missing most of the feature details).

[/feature/{id}](https://www.chromestatus.com/feature/5666372071718912)

<img width="825" alt="screen shot 2017-07-03 at 2 26 15 pm" src="https://user-images.githubusercontent.com/2294695/27804216-bc792b14-5ffb-11e7-820f-cfcd06fb450e.png">

[/features/{id}](https://www.chromestatus.com/features/5666372071718912)

<img width="807" alt="screen shot 2017-07-03 at 2 26 31 pm" src="https://user-images.githubusercontent.com/2294695/27804247-e25925aa-5ffb-11e7-968f-a801b9d37d3c.png">

This isn't fixed yet (IMHO), and may have regressed since being filed originally.

**Comment by ebidel** [comment]
Indeedd. Regressed and addressed in: https://github.com/GoogleChrome/chromium-dashboard/commit/3dd146ce9c95c48d1e0b2caa500ac8f00b8c04ab

**Comment by jrobbins** [comment]
The whole site was restyled several months ago.  The pages have consistent style now.  The top part of the individual feature page still shows only a subset of information about the feature, but there is an expandable section that shows all details.
