### ISSUE TITLE
Display of status entries is messed up

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/chromium-dashboard#727]
* The help icon next to the search box is bumping to the next line.
* Display of a selected item is showing a scroll bar and cutting off instead of using all the available space.

![image](https://user-images.githubusercontent.com/8204171/72816750-7ef62480-3c1d-11ea-8843-97c2f3a078c5.png)

**Comment by jrobbins** [comment]
My thinking is that the scroll bar is due to the height of the lit-virtualizer in chromedash-featurelist being calculated when the feature is collapsed and then the list as a whole is not getting taller when a feature is expanded.  I see a min-height style being set.  Using overflow:visible seems to fix it, but I need to test more.

**Comment by jrobbins** [comment]
I believe that this is resolved now.  The app no longer uses the element that made displaying that list tricky.  Now it is just a bunch of HTML elements all in the DOM.

**Comment by jpmedley** [comment]
Thanks!

**Comment by jpmedley** [comment]
The help icon is still getting bumped. 

![image](https://user-images.githubusercontent.com/8204171/73010359-25315e00-3dc7-11ea-9cea-8b3b76be03b8.png)

**Comment by jrobbins** [comment]
Doh, I'll look at that part now.

**Comment by jrobbins** [comment]
The help icon should stay at the end of the search box now.
You may need to refresh the page to get the updated CSS file.
